version: '3'

services:
  bitwarden:
    image: vaultwarden/server:1.29.1
    container_name: bitwarden
    restart: unless-stopped

    volumes:
      - /storage/data/bitwarden:/data
    ports:
      - 3011:80
      - 3012:3012
    environment:
      RUST_BACKTRACE: '1'
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'true'

  bw_backup:
    image: bruceforce/vaultwarden-backup
    container_name: backup
    restart: unless-stopped

    init: true
    depends_on:
      - bitwarden
    volumes:
      - /storage/data/bitwarden:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VW_DATABASE_URL=/data/db.sqlite3
      - BACKUP_DIR=/data/backup
      - BACKUP_DIR_PERMISSIONS=700
      - CRON_TIME=0 20 * * *
      - TIMESTAMP=false
      - UID=0
      - GID=0
