version: '3'

services:
  bitwarden:
    image: vaultwarden/server
    container_name: bitwarden
    restart: unless-stopped

    volumes:
      - /storage/data/bitwarden:/data
    ports:
      - 3011:80
      - 3012:3012
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'true'

  bw_backup:
    image: bruceforce/bw_backup
    container_name: backup
    restart: unless-stopped

    init: true
    depends_on:
      - bitwarden
    volumes:
      - /storage/data/bitwarden:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_FILE=/data/db.sqlite3
      - BACKUP_FILE=/data/backup/backup.sqlite3
      - CRON_TIME=0 20 * * *
      - TIMESTAMP=false
      - UID=0
      - GID=0
      - BACKUP_FILE_PERMISSIONS=700
