FROM homeassistant/home-assistant

RUN wget -O /usr/local/bin/ssl-cert-check https://raw.githubusercontent.com/Matty9191/ssl-cert-check/master/ssl-cert-check
RUN chmod +x /usr/local/bin/ssl-cert-check
