esphome:
  name: white_noise
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "White Noise Fallback Hotspot"
    password: "7iqs83F0Ful4"

captive_portal:
logger:
  level: VERBOSE
api:
ota:

uart:
  tx_pin: D1
  rx_pin: D2
  baud_rate: 9600

status_led:
  pin:
    number: GPIO2
    inverted: true

dfplayer:

output:
  - platform: gpio
    id: led
    pin: D5

binary_sensor:
  - platform: gpio
    id: reset
    name: White Noise Reset
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_release:
      then:
        - switch.toggle: track_airplane

light:
  - platform: binary
    id: status
    name: White Noise Status
    output: led

switch:
  - platform: template
    id: track_airplane
    name: Airplane Cabin
    optimistic: true
    turn_on_action:
      then:
        - light.turn_on: status
        - dfplayer.set_volume: 20
        - wait_until:
            switch.is_on: track_airplane
        - dfplayer.play: 1
        - delay: 2900ms
        - while: 
            condition:
              switch.is_on: track_airplane
            then:
              - dfplayer.play: 2
              - delay: 6s
    
    turn_off_action:
      then:
        - light.turn_off: status
        - dfplayer.play: 3
